# Generated by Django 4.2.16 on 2024-11-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trade_place',
            field=models.ForeignKey(db_comment='Идентификатор торгового места', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='markets.tradeplace'),
        ),
    ]
