# Generated by Django 4.2.16 on 2024-12-07 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('itn', models.CharField(max_length=12, validators=[markets.models.Validators.itn])),
            ],
            options={
                'verbose_name': 'Доп. данные',
                'verbose_name_plural': 'Доп. данные',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=512)),
                ('file_content', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='auxuserdata',
            name='passport_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passport_image', to='markets.file'),
        ),
        migrations.AddField(
            model_name='auxuserdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aux_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auxuserdata',
            name='usr_le_extract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usr_le_extract', to='markets.file'),
        ),
    ]
