# Generated by Django 4.2.16 on 2024-11-22 14:56

from django.db import migrations, models
import django.db.models.deletion
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='geo_city',
            field=models.ForeignKey(db_comment='Город - id', default=markets.models.Locality.default_pk, on_delete=django.db.models.deletion.DO_NOTHING, to='markets.locality'),
        ),
        migrations.AlterField(
            model_name='market',
            name='geo_district',
            field=models.ForeignKey(db_comment='Район - id', default=markets.models.Locality.default_pk, on_delete=django.db.models.deletion.DO_NOTHING, related_name='markets_geo_district_set', to='markets.locality'),
        ),
    ]
