# Generated by Django 4.2.16 on 2024-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tradeplace',
            name='index_by_number',
        ),
        migrations.RemoveIndex(
            model_name='tradeplace',
            name='index_by_storey',
        ),
        migrations.AddIndex(
            model_name='tradeplace',
            index=models.Index(fields=['location_number'], name='index_by_number'),
        ),
    ]
