# Generated by Django 4.2.16 on 2024-11-24 22:37

from django.db import migrations, models
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeplacetype',
            name='color',
            field=models.CharField(db_comment='Цвет в формате #ffffff', default='#ffffff', max_length=7, validators=[markets.models.Validators.css_color]),
        ),
        migrations.AlterField(
            model_name='tradespectype',
            name='color',
            field=models.CharField(db_comment='Цвет в формате #ffffff', default='#ffffff', max_length=7, validators=[markets.models.Validators.css_color]),
        ),
    ]
