# Generated by Django 4.2.16 on 2024-12-18 12:26

from django.db import migrations, models
import django.db.models.deletion
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Не указано', max_length=128)),
                ('image', models.ImageField(upload_to='contacts/%Y/%m/%d')),
                ('address', models.CharField(default='Не указано', max_length=256)),
                ('city', models.ForeignKey(default=markets.models.Locality.default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='markets.locality')),
                ('district', models.ForeignKey(default=markets.models.Locality.default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='another_contact_set', to='markets.locality')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='market',
            name='market_id',
            field=models.CharField(db_comment='Уникальный идентификатор рынка', max_length=3, unique=True, validators=[markets.models.Validators.market_id]),
        ),
        migrations.AlterField(
            model_name='marketphone',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='markets.contact')),
            ],
            options={
                'verbose_name': 'Контактный телефон',
                'verbose_name_plural': 'Контактные телефоны',
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='markets.contact')),
            ],
            options={
                'verbose_name': 'Контактный email',
                'verbose_name_plural': 'Контактные email',
            },
        ),
    ]
