# Generated by Django 4.2.16 on 2024-12-20 13:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='infr_entrance',
            field=models.SmallIntegerField(db_comment='Кол-во подъездов', default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='market',
            name='infr_parking',
            field=models.SmallIntegerField(db_comment='Кол-во парковок', default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='market',
            name='infr_restroom',
            field=models.SmallIntegerField(db_comment='Кол-во санузлов', default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='market',
            name='infr_sewerage_type',
            field=models.CharField(db_comment='Тип канализации', default='Не указано', max_length=64),
        ),
        migrations.AlterField(
            model_name='market',
            name='infr_storage',
            field=models.SmallIntegerField(db_comment='Кол-во складских помещений', default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='market',
            name='lat',
            field=models.FloatField(db_comment='Широта - координата рынка', default=0.0, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='market',
            name='lng',
            field=models.FloatField(db_comment='Долгота - координата рынка', default=0.0, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='tradeplace',
            name='impr_internet_type_id',
            field=models.SmallIntegerField(db_comment='Тип подключения к сети интернет (0 - не заполнено, 1 - проводной, 2 - беспроводной)', default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='tradeplace',
            name='meas_area',
            field=models.FloatField(db_comment='Площадь места', default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tradeplace',
            name='meas_height',
            field=models.FloatField(db_comment='Высота места', default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tradeplace',
            name='meas_length',
            field=models.FloatField(db_comment='Длина места', default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tradeplace',
            name='meas_width',
            field=models.FloatField(db_comment='Ширина места', default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tradeplace',
            name='price',
            field=models.DecimalField(db_comment='Стоимость аренды торгового места в месяц', decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
