# Generated by Django 4.2.16 on 2024-11-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(blank=True, db_column='ng_user', db_comment='Кто забронировал (NULL для старых броней)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trade_place',
            field=models.ForeignKey(db_comment='Идентификатор торгового места', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='markets.tradeplace'),
        ),
    ]
