# Generated by Django 4.2.16 on 2024-11-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstatustype',
            name='type_name',
            field=models.CharField(db_comment='Наименование типа специализации торгового места', unique=True),
        ),
        migrations.AlterField(
            model_name='localitytype',
            name='type_name',
            field=models.CharField(db_comment='Наименование типа', unique=True),
        ),
        migrations.AlterField(
            model_name='marketfireprotection',
            name='fp_name',
            field=models.CharField(db_comment='Наименование противопожарной системы', unique=True),
        ),
        migrations.AlterField(
            model_name='marketprofitability',
            name='profitability_name',
            field=models.CharField(db_comment='Наименование категории рентабельности рынка', unique=True),
        ),
        migrations.AlterField(
            model_name='markettype',
            name='type_name',
            field=models.CharField(db_comment='Наименование типа рынка', unique=True),
        ),
        migrations.AlterField(
            model_name='rentertype',
            name='type_name',
            field=models.CharField(db_comment='Наименование типа арендатора', unique=True),
        ),
        migrations.AlterField(
            model_name='streettype',
            name='type_name',
            field=models.CharField(db_comment='Наименование типа улиц (сокращенное)', unique=True),
        ),
        migrations.AlterField(
            model_name='tradeplacetype',
            name='type_name',
            field=models.CharField(db_comment='Наименование типа занятости торгового места', unique=True),
        ),
        migrations.AlterField(
            model_name='tradesector',
            name='sector_name',
            field=models.CharField(db_comment='Наименование сектора рынка', unique=True),
        ),
        migrations.AlterField(
            model_name='tradespectype',
            name='type_name',
            field=models.CharField(db_comment='Наименование типа специализации торгового места', unique=True),
        ),
        migrations.AlterField(
            model_name='tradetype',
            name='type_name',
            field=models.CharField(db_comment='Наименование типа торгового места', unique=True),
        ),
    ]
