# Generated by Django 4.2.16 on 2024-11-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractStatusType',
        ),
    ]
