# Generated by Django 4.2.16 on 2024-11-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='obsolete_user',
            field=models.ForeignKey(blank=True, db_column='user', db_comment='Кто забронировал (в старой версии БД)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='markets.user'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location_number',
            field=models.CharField(blank=True, db_comment='Номер торгового места (по странной логике ДЦТ, сюда падают номера которых нет в базе -- мы даем отлуп)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='renter_id',
            field=models.DecimalField(blank=True, db_comment='Арендатор (пользователь из внешнего источника, надо искать в базе)', decimal_places=0, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='user_id_transaction',
            field=models.ForeignKey(db_column='user_id_transaction', db_comment='id создателя (в старой БД)', null=True, on_delete=django.db.models.deletion.CASCADE, to='markets.user'),
        ),
    ]
