# Generated by Django 4.2.16 on 2024-09-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstatustype',
            name='descr',
            field=models.TextField(blank=True, db_comment='Описание', null=True),
        ),
        migrations.AlterField(
            model_name='tradespectype',
            name='descr',
            field=models.TextField(blank=True, db_comment='Описание', null=True),
        ),
        migrations.AlterField(
            model_name='tradetype',
            name='descr',
            field=models.TextField(blank=True, db_comment='Описание', null=True),
        ),
    ]
