# Generated by Django 4.2.16 on 2024-10-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_mkimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svgschema',
            name='market',
            field=models.ForeignKey(blank=True, db_comment='id рынка', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schemes', to='markets.market'),
        ),
    ]
