# Generated by Django 4.2.16 on 2024-11-24 19:21

from django.db import migrations, models
import django.db.models.deletion
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_locality_locality_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='locality_type',
            field=models.ForeignKey(db_comment='Тип населенного пункта', default=markets.models.LocalityType.default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='markets.localitytype'),
        ),
    ]
