# Generated by Django 4.2.16 on 2024-11-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_booking_booked_by_alter_booking_trade_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svgschema',
            name='order',
            field=models.IntegerField(blank=True, db_comment='Поле для упорядочивания схем', default=0, null=True),
        ),
    ]
