# Generated by Django 4.2.16 on 2024-11-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_market_geo_city_alter_market_geo_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='geo_house',
            field=models.CharField(db_comment='Дом', default='Не указан', max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='geo_street',
            field=models.TextField(db_comment='Наименование улицы', default='Не указана'),
        ),
    ]
