# Generated by Django 4.2.16 on 2024-09-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_contractstatustype_descr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markets',
            name='info_constitutive_files',
            field=models.JSONField(blank=True, db_comment='Копии правоустанавливающих документов дочернего предприятия - файлы', null=True),
        ),
        migrations.AlterField(
            model_name='markets',
            name='info_contracts_req',
            field=models.TextField(blank=True, db_comment='Информация о требованиях для оформления договоров/талонов', null=True),
        ),
        migrations.AlterField(
            model_name='markets',
            name='info_contracts_req_files',
            field=models.JSONField(blank=True, db_comment='Требованиях для оформления договоров/талонов - файлы', null=True),
        ),
        migrations.AlterField(
            model_name='markets',
            name='info_statement_forms',
            field=models.TextField(blank=True, db_comment='Информация о формах заявлений', null=True),
        ),
        migrations.AlterField(
            model_name='tradecontract',
            name='contract_status_type',
            field=models.ForeignKey(db_comment='id статус договора', on_delete=django.db.models.deletion.DO_NOTHING, to='markets.contractstatustype'),
        ),
        migrations.AlterField(
            model_name='tradecontract',
            name='copy_files',
            field=models.JSONField(blank=True, db_comment='Файлы договора', null=True),
        ),
        migrations.AlterField(
            model_name='tradecontract',
            name='copy_info',
            field=models.CharField(blank=True, db_comment='Информация о копии договора', null=True),
        ),
        migrations.AlterField(
            model_name='tradecontract',
            name='date_end',
            field=models.DateField(blank=True, db_comment='Дата окончания договора', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, db_comment='Фамилия Имя Отчество пользователя', max_length=255, null=True),
        ),
    ]
