# Generated by Django 4.2.16 on 2024-11-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_remove_tradeplace_index_by_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeplace',
            name='location_floor',
        ),
    ]
