# Generated by Django 4.2.16 on 2024-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_market_infr_entrance_alter_market_infr_parking_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(check=models.Q(('infr_parking__gte', 0)), name='non negative parking'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(check=models.Q(('infr_entrance__gte', 0)), name='non negative entrance'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(check=models.Q(('infr_restroom__gte', 0)), name='non negative restroom'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(check=models.Q(('infr_storage__gte', 0)), name='non negative storage'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(check=models.Q(('market_area__gte', 0.0)), name='non negative market area'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(check=models.Q(('lat__gte', -90.0), ('lat__lte', 90.0)), name='lat range'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(check=models.Q(('lng__gte', -180.0), ('lat__lte', 180.0)), name='lng range'),
        ),
    ]
