# Generated by Django 4.2.16 on 2024-12-07 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auxuserdata_file_delete_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeplace',
            name='pay_add_equipment',
        ),
        migrations.RemoveField(
            model_name='tradeplace',
            name='pay_air_conditioning',
        ),
        migrations.RemoveField(
            model_name='tradeplace',
            name='pay_drains',
        ),
        migrations.RemoveField(
            model_name='tradeplace',
            name='pay_electricity',
        ),
        migrations.RemoveField(
            model_name='tradeplace',
            name='pay_fridge',
        ),
        migrations.RemoveField(
            model_name='tradeplace',
            name='pay_heat_supply',
        ),
        migrations.RemoveField(
            model_name='tradeplace',
            name='pay_internet',
        ),
        migrations.RemoveField(
            model_name='tradeplace',
            name='pay_plumbing',
        ),
        migrations.RemoveField(
            model_name='tradeplace',
            name='pay_sewerage',
        ),
        migrations.RemoveField(
            model_name='tradeplace',
            name='pay_shopwindows',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(db_comment='Кто забронировал', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(db_comment='Идентификатор торгового места', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='markets.tradeplace')),
            ],
            options={
                'verbose_name': 'Бронирование ТМ',
                'verbose_name_plural': 'Бронирования ТМ',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
