# Generated by Django 4.2.16 on 2024-12-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_market_non_negative_parking_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='market',
            name='non negative parking',
        ),
        migrations.RemoveConstraint(
            model_name='market',
            name='non negative entrance',
        ),
        migrations.RemoveConstraint(
            model_name='market',
            name='non negative restroom',
        ),
        migrations.RemoveConstraint(
            model_name='market',
            name='non negative storage',
        ),
        migrations.RemoveConstraint(
            model_name='market',
            name='non negative market area',
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(check=models.Q(('infr_parking__gte', 0)), name='non-negative parking'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(check=models.Q(('infr_entrance__gte', 0)), name='non-negative entrance'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(check=models.Q(('infr_restroom__gte', 0)), name='non-negative restroom'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(check=models.Q(('infr_storage__gte', 0)), name='non-negative storage'),
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.CheckConstraint(check=models.Q(('market_area__gte', 0.0)), name='non-negative market area'),
        ),
        migrations.AddConstraint(
            model_name='tradeplace',
            constraint=models.CheckConstraint(check=models.Q(('meas_area__gte', 0.0)), name='non-negative area'),
        ),
        migrations.AddConstraint(
            model_name='tradeplace',
            constraint=models.CheckConstraint(check=models.Q(('meas_length__gte', 0.0)), name='non-negative length'),
        ),
        migrations.AddConstraint(
            model_name='tradeplace',
            constraint=models.CheckConstraint(check=models.Q(('meas_height__gte', 0.0)), name='non-negative height'),
        ),
        migrations.AddConstraint(
            model_name='tradeplace',
            constraint=models.CheckConstraint(check=models.Q(('meas_width__gte', 0.0)), name='non-negative width'),
        ),
        migrations.AddConstraint(
            model_name='tradeplace',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0.0)), name='non-negative price'),
        ),
    ]
