# Generated by Django 4.2.16 on 2024-11-11 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdata',
            name='created_by',
            field=models.ForeignKey(blank=True, db_comment='id создателя (NULL для старых записей)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
