# Generated by Django 4.2.16 on 2024-10-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_alter_svgschema_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=250)),
                ('preload', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.AlterModelOptions(
            name='globalconfig',
            options={'managed': True, 'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'managed': True, 'verbose_name': 'Рынок', 'verbose_name_plural': 'Рынки'},
        ),
        migrations.AlterModelOptions(
            name='svgschema',
            options={'managed': True, 'verbose_name': 'Схема', 'verbose_name_plural': 'Схемы'},
        ),
    ]
