# Generated by Django 4.2.16 on 2024-11-26 18:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_remove_tradeplace_location_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('decimal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
            },
        ),
        migrations.CreateModel(
            name='MarketObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50)),
                ('decimal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='markets.market')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
            },
        ),
        migrations.AddConstraint(
            model_name='marketobservation',
            constraint=models.UniqueConstraint(fields=('key', 'market_id'), name='unique_key_per_market'),
        ),
    ]
