# Generated by Django 4.2.16 on 2024-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_alter_svgschema_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svgschema',
            name='order',
            field=models.IntegerField(db_comment='Поле для упорядочивания схем', default=0),
        ),
    ]
