# Generated by Django 4.2.16 on 2024-12-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_remove_market_non_negative_parking_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tradeplace',
            constraint=models.CheckConstraint(check=models.Q(('impr_internet_type_id__gte', 0), ('impr_internet_type_id__lte', 2)), name='internet_type_id range'),
        ),
    ]
