# Generated by Django 4.2.16 on 2024-10-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_parameter_alter_globalconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradeplacetype',
            options={'managed': True, 'verbose_name': 'Тип занятости ТМ', 'verbose_name_plural': 'Типы занятости ТМ'},
        ),
        migrations.AddField(
            model_name='tradeplacetype',
            name='roof_color',
            field=models.CharField(db_comment='Цвет крыш ТМ в формате 0xffffff, для 3D', default='0xffffff', max_length=8),
        ),
        migrations.AddField(
            model_name='tradeplacetype',
            name='wall_color',
            field=models.CharField(db_comment='Цвет стен ТМ в формате 0xffffff, для 3D', default='0xffffff', max_length=8),
        ),
    ]
