# Generated by Django 4.2.16 on 2024-12-09 12:17

from django.db import migrations, models
import markets.enums


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_auxuserdata_promo_image_auxuserdata_promo_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeplacetype',
            name='type_name',
            field=models.CharField(choices=[(markets.enums.OutletState['UNKNOWN'], 'Не указано'), (markets.enums.OutletState['AVAILABLE_FOR_BOOKING'], 'Свободно'), (markets.enums.OutletState['UNAVAILABLE_FOR_BOOKING'], 'Не сдаётся в аренду'), (markets.enums.OutletState['TEMPORARILY_UNAVAILABLE_FOR_BOOKING'], 'Временно не сдается в аренду'), (markets.enums.OutletState['BOOKED'], 'Забронировано'), (markets.enums.OutletState['RENTED'], 'Занято')], db_comment='Наименование типа занятости торгового места', max_length=10, unique=True),
        ),
    ]
