# Generated by Django 4.2.16 on 2024-10-21 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_alter_tradeplacetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeplace',
            name='market',
            field=models.ForeignKey(db_comment='Уникальный идентификатор рынка\r\n', on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade_places', to='markets.market'),
        ),
    ]
