# Generated by Django 4.2.16 on 2024-12-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_alter_notification_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='type values from set',
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['info', 'warn', 'alrt'])), name='type values from set'),
        ),
    ]
