# Generated by Django 4.2.16 on 2024-10-25 13:18

from django.db import migrations, models
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_alter_tradeplace_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeplacetype',
            name='color',
            field=models.CharField(blank=True, db_comment='Цвет в формате #ffffff', max_length=7, null=True, validators=[markets.models.Validators.css_color]),
        ),
        migrations.AlterField(
            model_name='tradeplacetype',
            name='roof_color',
            field=models.CharField(db_comment='Цвет крыш ТМ в формате 0xffffff, для 3D', default='0xffffff', max_length=8, validators=[markets.models.Validators.hex]),
        ),
        migrations.AlterField(
            model_name='tradeplacetype',
            name='wall_color',
            field=models.CharField(db_comment='Цвет стен ТМ в формате 0xffffff, для 3D', default='0xffffff', max_length=8, validators=[markets.models.Validators.hex]),
        ),
    ]
