# Generated by Django 4.2.16 on 2025-01-07 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_remove_notification_type_values_from_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeplace',
            name='rented_by',
            field=models.ForeignKey(db_comment='кем арендовано', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rented_outlets', to=settings.AUTH_USER_MODEL),
        ),
    ]
