# Generated by Django 4.2.16 on 2024-11-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_alter_tradeplacetype_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdcError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Ошибка',
                'verbose_name_plural': 'Ошибки',
            },
        ),
    ]
