# Generated by Django 4.2.16 on 2025-01-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_alter_tradeplace_rented_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='question_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(max_length=4096),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['question_uuid'], name='index_by_question_uuid'),
        ),
    ]
