# Generated by Django 4.2.16 on 2024-11-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_rdcerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuffAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('link', models.URLField(default='', max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['title'],
            },
        ),
    ]
