# Generated by Django 4.2.16 on 2025-01-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_notification_question_uuid_alter_notification_text_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', True), ('question_uuid__isnull', False), _negated=True), name="broadcast notification can not be 'question'"),
        ),
    ]
