# Generated by Django 4.2.16 on 2024-11-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_stuffaction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tradeplace',
            index=models.Index(fields=['location_number'], include=('location_floor',), name='index_by_number'),
        ),
        migrations.AddIndex(
            model_name='tradeplace',
            index=models.Index(fields=['location_floor'], include=('location_number',), name='index_by_storey'),
        ),
    ]
