# Generated by Django 4.2.16 on 2024-11-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_tradeplace_index_by_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtradeplace',
            name='location_number',
            field=models.CharField(blank=True, db_comment='Номер торгового места', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tradeplace',
            name='location_number',
            field=models.CharField(blank=True, db_comment='Номер торгового места', null=True, unique=True),
        ),
    ]
