# Generated by Django 4.2.16 on 2025-01-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_notification_broadcast_notification_can_not_be_question_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='question_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
