# Generated by Django 4.2.16 on 2024-11-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0011_alter_importtradeplace_location_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': True, 'verbose_name': 'Бронирование ТМ', 'verbose_name_plural': 'Бронирования ТМ'},
        ),
        migrations.AlterModelOptions(
            name='contractstatustype',
            options={'managed': True, 'verbose_name': 'Тип статуса договора', 'verbose_name_plural': 'Типы статуса договора'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'managed': True, 'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='localitytype',
            options={'managed': True, 'verbose_name': 'Тип локации', 'verbose_name_plural': 'Типы локаций'},
        ),
        migrations.AlterModelOptions(
            name='marketfireprotection',
            options={'managed': True, 'verbose_name': 'Тип противопожарной системы', 'verbose_name_plural': 'Типы противопожарных систем'},
        ),
        migrations.AlterModelOptions(
            name='marketprofitability',
            options={'managed': True, 'verbose_name': 'Категория рентабельности рынка', 'verbose_name_plural': 'Категории рентабельности рынка'},
        ),
        migrations.AlterModelOptions(
            name='markettype',
            options={'managed': True, 'verbose_name': 'Тип рынка', 'verbose_name_plural': 'Типы рынка'},
        ),
        migrations.AlterModelOptions(
            name='renter',
            options={'managed': True, 'verbose_name': 'Арендатор', 'verbose_name_plural': 'Арендаторы'},
        ),
        migrations.AlterModelOptions(
            name='rentertype',
            options={'managed': True, 'verbose_name': 'Тип арендатора', 'verbose_name_plural': 'Типы арендаторов'},
        ),
        migrations.AlterModelOptions(
            name='streettype',
            options={'managed': True, 'verbose_name': 'Тип улицы', 'verbose_name_plural': 'Типы улиц'},
        ),
        migrations.AlterModelOptions(
            name='tradecontract',
            options={'managed': True, 'verbose_name': 'Договор аренды', 'verbose_name_plural': 'Договоры аренды'},
        ),
        migrations.AlterModelOptions(
            name='tradeplace',
            options={'managed': True, 'verbose_name': 'Торговое место', 'verbose_name_plural': 'Торговые места'},
        ),
        migrations.AlterModelOptions(
            name='tradesector',
            options={'managed': True, 'verbose_name': 'Сектор', 'verbose_name_plural': 'Секторы'},
        ),
        migrations.AlterModelOptions(
            name='tradespectype',
            options={'managed': True, 'verbose_name': 'Тип специализации ТМ', 'verbose_name_plural': 'Типы специализации ТМ'},
        ),
        migrations.AlterModelOptions(
            name='tradetype',
            options={'managed': True, 'verbose_name': 'Тип ТМ', 'verbose_name_plural': 'Типы ТМ'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
