# Generated by Django 4.2.16 on 2025-01-13 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markets.enums


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0011_alter_notification_question_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(default=markets.enums.LogRecordKind['INFO'], max_length=10)),
                ('text', models.TextField(max_length=1024)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Записи журнала',
                'ordering': ['created_at'],
            },
        ),
    ]
