# Generated by Django 4.2.16 on 2024-11-06 19:07

from django.db import migrations, models
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0012_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtradeplace',
            name='location_number',
            field=models.CharField(blank=True, db_comment='Номер торгового места', null=True, unique=True, validators=[markets.models.Validators.outlet_number]),
        ),
        migrations.AlterField(
            model_name='tradeplace',
            name='location_number',
            field=models.CharField(blank=True, db_comment='Номер торгового места', null=True, unique=True, validators=[markets.models.Validators.outlet_number]),
        ),
    ]
