# Generated by Django 4.2.16 on 2025-01-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0012_logrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxuserdata',
            name='promo_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
