# Generated by Django 4.2.16 on 2024-11-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0013_alter_importtradeplace_location_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': True, 'ordering': ['-date_transaction'], 'verbose_name': 'Бронирование ТМ', 'verbose_name_plural': 'Бронирования ТМ'},
        ),
        migrations.AlterModelOptions(
            name='contractstatustype',
            options={'managed': True, 'ordering': ['type_name'], 'verbose_name': 'Тип статуса договора', 'verbose_name_plural': 'Типы статуса договора'},
        ),
        migrations.AlterModelOptions(
            name='globalconfig',
            options={'managed': True, 'ordering': ['param_name'], 'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterModelOptions(
            name='importdata',
            options={'managed': True, 'ordering': ['-date_transaction']},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'managed': True, 'ordering': ['locality_name'], 'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='localitytype',
            options={'managed': True, 'ordering': ['type_name'], 'verbose_name': 'Тип локации', 'verbose_name_plural': 'Типы локаций'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'managed': True, 'ordering': ['market_name', 'additional_name'], 'verbose_name': 'Рынок', 'verbose_name_plural': 'Рынки'},
        ),
        migrations.AlterModelOptions(
            name='marketfireprotection',
            options={'managed': True, 'ordering': ['fp_name'], 'verbose_name': 'Тип противопожарной системы', 'verbose_name_plural': 'Типы противопожарных систем'},
        ),
        migrations.AlterModelOptions(
            name='marketprofitability',
            options={'managed': True, 'ordering': ['profitability_name'], 'verbose_name': 'Категория рентабельности рынка', 'verbose_name_plural': 'Категории рентабельности рынка'},
        ),
        migrations.AlterModelOptions(
            name='markettype',
            options={'managed': True, 'ordering': ['type_name'], 'verbose_name': 'Тип рынка', 'verbose_name_plural': 'Типы рынка'},
        ),
        migrations.AlterModelOptions(
            name='renter',
            options={'managed': True, 'ordering': ['renter_name'], 'verbose_name': 'Арендатор', 'verbose_name_plural': 'Арендаторы'},
        ),
        migrations.AlterModelOptions(
            name='rentertype',
            options={'managed': True, 'ordering': ['type_name'], 'verbose_name': 'Тип арендатора', 'verbose_name_plural': 'Типы арендаторов'},
        ),
        migrations.AlterModelOptions(
            name='streettype',
            options={'managed': True, 'ordering': ['type_name'], 'verbose_name': 'Тип улицы', 'verbose_name_plural': 'Типы улиц'},
        ),
        migrations.AlterModelOptions(
            name='svgschema',
            options={'managed': True, 'ordering': ['order'], 'verbose_name': 'Схема', 'verbose_name_plural': 'Схемы'},
        ),
        migrations.AlterModelOptions(
            name='tradeplace',
            options={'managed': True, 'ordering': ['location_number'], 'verbose_name': 'Торговое место', 'verbose_name_plural': 'Торговые места'},
        ),
        migrations.AlterModelOptions(
            name='tradeplacetype',
            options={'managed': True, 'ordering': ['type_name'], 'verbose_name': 'Тип занятости ТМ', 'verbose_name_plural': 'Типы занятости ТМ'},
        ),
        migrations.AlterModelOptions(
            name='tradesector',
            options={'managed': True, 'ordering': ['sector_name'], 'verbose_name': 'Сектор', 'verbose_name_plural': 'Секторы'},
        ),
        migrations.AlterModelOptions(
            name='tradespectype',
            options={'managed': True, 'ordering': ['type_name'], 'verbose_name': 'Тип специализации ТМ', 'verbose_name_plural': 'Типы специализации ТМ'},
        ),
        migrations.AlterModelOptions(
            name='tradetype',
            options={'managed': True, 'ordering': ['type_name'], 'verbose_name': 'Тип ТМ', 'verbose_name_plural': 'Типы ТМ'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='svgschema',
            name='order',
            field=models.IntegerField(db_comment='Поле для упорядочивания схем', default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trade_place',
            field=models.ForeignKey(db_comment='Идентификатор торгового места', on_delete=django.db.models.deletion.DO_NOTHING, to='markets.tradeplace'),
        ),
    ]
