# Generated by Django 4.2.18 on 2025-02-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0013_auxuserdata_promo_enabled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RdcError',
        ),
    ]
