# Generated by Django 4.2.16 on 2024-11-09 20:30

from django.db import migrations, models
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0014_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradespectype',
            name='roof_color',
            field=models.CharField(db_comment='Цвет крыш ТМ в формате 0xffffff, для 3D', default='0xffffff', max_length=8, validators=[markets.models.Validators.hex]),
        ),
        migrations.AddField(
            model_name='tradespectype',
            name='wall_color',
            field=models.CharField(db_comment='Цвет стен ТМ в формате 0xffffff, для 3D', default='0xffffff', max_length=8, validators=[markets.models.Validators.hex]),
        ),
    ]
