services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    image: nginx:1.27
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ./:/code
    ports:
      - "80:80"
    depends_on:
      - web
  cache:
    image: redis:7.4
    restart: always
    volumes:
      - ./data/cache:/data
  rabbit:
    image: rabbitmq:latest
    restart: always
  web:
    build: .
    command: daphne -b web -p 8000 dmarks.asgi:application
    restart: always
    volumes:
      - ./:/code
    environment:
      - DJANGO_SETTINGS_MODULE=dmarks.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_DB=0
      - RABBIT=rabbit
      - TELEBOT=7995656642:AAE2BD5BZME2rQXbg6OHv0nEAVpGCu_JGLA
    depends_on:
      - db
      - cache
  celery:
    build: .
    command: celery -A dmarks worker -l INFO
    restart: always
    volumes:
      - ./:/code
    environment:
      - DJANGO_SETTINGS_MODULE=dmarks.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_DB=0
      - RABBIT=rabbit
      - TELEBOT=7995656642:AAE2BD5BZME2rQXbg6OHv0nEAVpGCu_JGLA
    depends_on:
      - rabbit
      - web
  celery_beat:
    build: .
    command: celery -A dmarks beat --max-interval 86400
    restart: always
    volumes:
      - ./:/code
    environment:
      - DJANGO_SETTINGS_MODULE=dmarks.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_DB=0
      - RABBIT=rabbit
      - TELEBOT=7995656642:AAE2BD5BZME2rQXbg6OHv0nEAVpGCu_JGLA
    depends_on:
      - rabbit
      - web
      - celery