services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    image: nginx:1.27
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ./:/code
    ports:
      - "80:80"
    depends_on:
      - web
  cache:
    image: redis:7.4
    restart: always
    volumes:
      - ./data/cache:/data
  web:
    build: .
    #--1-- command: gunicorn --bind=web:8000 dmarks.wsgi --workers 4 --threads 1 --log-file /code/gunicorn.log --log-level debug --preload
    #--2-- command: python manage.py runserver web:8000 --insecure
    #--3-- command: uwsgi --http :8000 --wsgi-file /code/dmarks/wsgi.py --processes 4 --threads 1
    command: gunicorn --bind=web:8000 dmarks.wsgi --workers 4 --threads 1 --log-file /code/gunicorn.log --log-level error --preload
    restart: always
    volumes:
      - ./:/code
    environment:
      - DJANGO_SETTINGS_MODULE=dmarks.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - db
      - cache

